# Generated by Django 4.0 on 2021-12-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Car')),
                ('place', models.IntegerField(default=4, verbose_name='Place')),
                ('max_speed', models.IntegerField(verbose_name='MaxSpeed')),
                ('hp', models.IntegerField(verbose_name='HorsePower')),
                ('drive_unit', models.CharField(default='4wd', max_length=150, verbose_name='DriveUnit')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('image', models.ImageField(upload_to='car_images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='Day')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('surname', models.CharField(max_length=150, verbose_name='Surname')),
                ('number', models.CharField(max_length=150, verbose_name='MobileNumber')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('fullFuel', models.BooleanField(default=True, verbose_name='FullFuel')),
                ('water', models.BooleanField(default=False, verbose_name='Water')),
                ('driver', models.BooleanField(default=False, verbose_name='Driver')),
                ('outOfTown', models.BooleanField(default=False, verbose_name='TripOutOfTown')),
                ('sweets', models.BooleanField(default=False, verbose_name='Sweets')),
                ('comments', models.TextField(max_length=250, verbose_name='Comments')),
                ('car', models.ManyToManyField(to='myLezgo.Car', verbose_name='cars')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='rate',
            field=models.ManyToManyField(to='myLezgo.Rate', verbose_name='rate'),
        ),
    ]
