# Generated by Django 4.0 on 2021-12-18 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myLezgo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rate',
        ),
    ]
