# Generated by Django 4.0 on 2021-12-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLezgo', '0002_remove_car_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rate',
            field=models.ManyToManyField(to='myLezgo.Rate', verbose_name='rate'),
        ),
    ]
