# Generated by Django 4.0 on 2021-12-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLezgo', '0003_car_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default='car', max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
